version: '3'

services:
  backend:
    image: 532123131998.dkr.ecr.us-east-2.amazonaws.com/expense-tracker-backend:latest
    mem_limit: 512m
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - JSON_LOGS=true
      - SERVER_NAME=ExpenseTracker
      - API_V1_STR=/api/v1
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - SERVER_HOST=http://localhost:8000
      - BACKEND_CORS_ORIGINS=["*"]
      - POSTGRES_SERVER=expense-tracker-db.c92mow8coz6a.us-east-2.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_DB=expense_tracker
      - SECRETS_ARN=${SECRETS_ARN}

  frontend:
    image: 532123131998.dkr.ecr.us-east-2.amazonaws.com/expense-tracker-frontend:latest
    mem_limit: 256m
    ports:
      - "80:80"
    depends_on:
      - backend 