version: '3'
services:
  backend:
    image: 532123131998.dkr.ecr.us-east-2.amazonaws.com/expense-tracker-backend:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - LOG_LEVEL=INFO
      - JSON_LOGS=true
      - ENVIRONMENT=production
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - SECRET_KEY=${SECRET_KEY}
      - SERVER_NAME=ExpenseTracker
      - API_V1_STR=/api/v1
      - SERVER_HOST=https://${EB_ENVIRONMENT_URL}
      - BACKEND_CORS_ORIGINS=["https://${EB_ENVIRONMENT_URL}", "http://${EB_ENVIRONMENT_URL}"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/monitoring/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: 532123131998.dkr.ecr.us-east-2.amazonaws.com/expense-tracker-frontend:latest
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s