"""add_cascade_delete_to_audit_records

Revision ID: 26269b7dd4f9
Revises: 6020ebbc8773
Create Date: 2025-04-28 23:30:55.666634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26269b7dd4f9'
down_revision = '6020ebbc8773'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audit_records_expense_id_fkey', 'audit_records', type_='foreignkey')
    op.create_foreign_key(None, 'audit_records', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_records', type_='foreignkey')
    op.create_foreign_key('audit_records_expense_id_fkey', 'audit_records', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###