"""add_is_active_to_expenses

Revision ID: ee59460ffbdf
Revises: 26269b7dd4f9
Create Date: 2025-04-28 23:34:19.886381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee59460ffbdf'
down_revision = '26269b7dd4f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero, añadir la columna como nullable para evitar errores
    op.add_column('expenses', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Establecer el valor por defecto para los registros existentes
    op.execute("UPDATE expenses SET is_active = TRUE")
    
    # Ahora cambiar la columna a NOT NULL
    op.alter_column('expenses', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_active')
    # ### end Alembic commands ###