"""enhance_audit_record_model

Revision ID: f455778d6328
Revises: ee59460ffbdf
Create Date: 2025-04-28 23:44:48.774255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Integer, JSON, Column, select, MetaData, Table


# revision identifiers, used by Alembic.
revision = 'f455778d6328'
down_revision = 'ee59460ffbdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero, agregar las nuevas columnas como nullable para poder llenarlas
    op.add_column('audit_records', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('audit_records', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('audit_records', sa.Column('new_data', sa.JSON(), nullable=True))
    op.alter_column('audit_records', 'expense_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    # Actualizar los registros existentes
    connection = op.get_bind()
    metadata = MetaData()
    
    # Definir tabla para poder hacer consultas y actualizaciones
    audit_records = Table(
        'audit_records',
        metadata,
        Column('id', Integer, primary_key=True),
        Column('entity_type', String),
        Column('entity_id', Integer),
        Column('expense_id', Integer),
        autoload_with=connection
    )
    
    # Actualizar registros existentes para establecer entity_type='expense' y entity_id=expense_id
    connection.execute(
        audit_records.update().values(
            entity_type='expense',
            entity_id=audit_records.c.expense_id
        )
    )
    
    # Ahora hacer que las columnas sean NOT NULL
    op.alter_column('audit_records', 'entity_type',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('audit_records', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_records', 'expense_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_records', 'new_data')
    op.drop_column('audit_records', 'entity_id')
    op.drop_column('audit_records', 'entity_type')
    # ### end Alembic commands ###